project:
  type: website
  output-dir: docs
  
website:
  title: "testwebsite"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Blog
        href: posts/index.qmd

format:
  html:
    theme: cosmo
    toc: true



