project:
  type: website
  output-dir: docs
  
website:
  title: "testwebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



